### ISSUE TITLE
ACL gestion

### ISSUE THREAD

**Issue by etienneboph** [xif-fr/dokuwiki-plugin-catlist#1]
Hi, 

It could be great if an user didn't see pages he can't have access to. 

Nevertheless, thank you for that great extension !

Best regards,

Etienne.

**Comment by xif-fr** [comment]
Hi,
Normally catlist checks some ACLs when generating links. Could you point be a particular example / expected behavior ?

**Comment by etienneboph** [comment]
Every pages appears when I put the following code : 

<catlist -noHead -noAddPageButton -maxDepth:1>

Difference is that people who doesn't have right to read a page, have the name's page in black instead of the link. Like that : 

![catlist-acl](https://user-images.githubusercontent.com/34281006/34564371-c0cb6320-f156-11e7-8f36-5d800c03c4b9.JPG)

It could be better if pages for which we don't have access were hidden.

**Comment by xif-fr** [comment]
Ok I see. I'll add an option for that when I'll have time, probably next week.

**Comment by etienneboph** [comment]
That would be awesome ! Thank you very much.

**Comment by xif-fr** [comment]
Hi, could you check if the `hide_acl_nsnotr` I added works for you (documented here : [https://www.dokuwiki.org/plugin:catlist#global_options](url)) ?

**Comment by etienneboph** [comment]
I don't know why, but when I put "<catlist -noHead -noAddPageButton hide_acl_nsnotr>", I've got the following error : "hide_acl_nsnotr category doesn't exist".

**Comment by xif-fr** [comment]
Ha, it's a global option. You can find it in your config manager. Maybe that's not what you wanted ?

**Comment by etienneboph** [comment]
Oh! Excuse me, I didn't understand. It works perfectly! Thank you very much!

**Comment by xif-fr** [comment]
Ok, I'll release this option in a new version.
