### ISSUE TITLE
Issue with Friendly URLs

### ISSUE THREAD

**Issue by MikeWills** [xif-fr/dokuwiki-plugin-catlist#11]
I love the plugin, however, I found an issue when using with Friendly URLs. When adding a new page from the listing the URL will be incorrect creating an unintended URL (https://mydomain.com/doku.php/podcast/ddop/s/test&do=edit). I am then presented with the "This topic does not exist yet" view then I have to click edit. When I do that page name becomes `test_do_edit`. I believe a test should be done to see if the setting `userewrite` is set to "DocuWiki Internal" then append a `?` instead of an `&`.

**Comment by xif-fr** [comment]
The intended URL should be https://mydomain.com/doku.php/podcast/ddop/s/test?do=edit right ? I already take into account `userewrite`, but I probably miss-implemented the case `userewrite=2`

**Comment by MikeWills** [comment]
Yes

**Comment by xif-fr** [comment]
I think I fixed it. Sorry for the looong delay. Could you check the last version ([https://github.com/xif-fr/dokuwiki-plugin-catlist/archive/master.zip](url)) ?

**Comment by MikeWills** [comment]
Works great now!
--
Mike Wills
http://mikewills.me
Ph: 507-933-0880

**Comment by xif-fr** [comment]
The 2018-10-04 version should do it by the way.
