### ISSUE TITLE
What is the proper syntax for -excludeOnName

### ISSUE THREAD

**Issue by MikeWills** [xif-fr/dokuwiki-plugin-catlist#12]
I am trying to use `-excludeOnName` to exclude my templates. However, I can't get it to work. The closest I can get is `-excludeOnName template` but that will throw the following error: 

     The namespace podcast:ddop:notes: template does not exist

What am I doing wrong or is it a bug?

**Comment by xif-fr** [comment]
It is a switch, not an option which takes an argument. If you want to exclude the `template` page, you can do `<catlist -excluPage:"template">`

**Comment by MikeWills** [comment]
Thanks, that did it. I was a bit confused in the documentation on that one.

**Comment by xif-fr** [comment]
Ok, I'll clarify the documentation, and add examples
