### ISSUE TITLE
Respect useheading setting

### ISSUE THREAD

**Issue by svenssonaxel** [xif-fr/dokuwiki-plugin-catlist#14]
When the setting "useheading" (in the Dokuwiki settings, Display section) is set to "Never", the text for links to pages default to the page name, rather than the first heading of that page. However, page links that are part of a catlist listing do not behave in this way.

I suggest catlist should at least obey the "useheading" setting by default. It might be useful to also add plugin-level settings to control this behavior. As it currently stands, there appears to be no way to make catlist show page names.

**Comment by xif-fr** [comment]
Yes, you're right, I should have respected 'useheading' from the beginning. But I don't want to break the current behavior, so I'll only add a plugin-level option, defaulting to 'yes'.

Thanks.

**Comment by svenssonaxel** [comment]
You're right, at this point that's probably the best solution.

**Comment by xif-fr** [comment]
I hope the 2018-10-04 version meets what you wanted.
