### ISSUE TITLE
use placeholders to define namespaces

### ISSUE THREAD

**Issue by jv-uzl** [xif-fr/dokuwiki-plugin-catlist#15]
Some plugins allow using placeholders such as @NS@, @USER@, @PAGE@, @ID@. This would be extremely useful for flexibly specifying the namespace parameter. Thanks!

**Comment by xif-fr** [comment]
Hi, could you give me some examples and desired behaviors ?

**Comment by jv-uzl** [comment]
Hi, thanks for replying and sorry for not giving examples right away. I'd like to be able to use placeholders similar to the ones that can be used in [namespace template pages](https://www.dokuwiki.org/namespace_templates) to create catlist expressions such as

<catlist userpages:@USER@: >     // replace @USER@ by id of currently logged-in user
<catlist projectpages:@PAGE@: >  // replace @PAGE@ by name (without namespace) of current page

[Medialist](https://www.dokuwiki.org/plugin:medialist) has a similar functionality, allowing placeholders @ID@, @NS@, @PAGE@.

(I'm using catlist in templates for the plugin [pagetemplater](https://www.dokuwiki.org/plugin:pagetemplater), meaning that I need to use a "variable" expression for catlist. Currently I'm using [phpwikify](https://www.dokuwiki.org/plugin:phpwikify) to create that expression, but there are security issues with that plugin.)

**Comment by xif-fr** [comment]
This is doable, I'll see if I can reuse some of the code from the template engine, if I have time.
But this feature should really be integrated in dokuwiki itself, because it could be useful with any plugin.

**Comment by xif-fr** [comment]
Implemented in the last version.

**Comment by juliusverrel** [comment]
thanks
