### ISSUE TITLE
list files with other extensions

### ISSUE THREAD

**Issue by shogunjames** [xif-fr/dokuwiki-plugin-catlist#16]
Hi 

Could you please adjust the plugin , so that it will list the files with extensions .ascii,.pdf,.ppt,.doc,.docx,.odt etc

**Comment by xif-fr** [comment]
Are you talking about files in the file manager itself or in the filesystem directory ?

**Comment by shogunjames** [comment]
i Mean files in the namespaces/directories.. if I put all files, it should
show..'

Is it possible?

**Comment by shogunjames** [comment]
i Mean files in the namespaces/directories.. if I put all files, it should show..'

Is it possible?

**Comment by shogunjames** [comment]
Hi Felix,

Some of the txt files are not showing , using this plugin?

Is there any restrictions?
