### ISSUE TITLE
PHP error "Only variables should be passed by reference"

### ISSUE THREAD

**Issue by bradbulger** [xif-fr/dokuwiki-plugin-catlist#19]
There's a line in syntax.php calling end() on the result of explode() - not allowed in modern PHP (I think since 5.3?)

`if (is_null($main['title'])) $main['title'] = end(explode(':', $ns));`

Needs to assign explode() to a variable first, like 

`if (is_null($main['title'])) {$nsparts = explode(':', $ns);$main['title'] = end($nsparts);}`

**Comment by xif-fr** [comment]
Thanks for the report, fixed in 35773a9a02edc35ca5315c5b1455b0dda789fa95

**Comment by xif-fr** [comment]
(I should release a new version very soon)
