### ISSUE TITLE
Error 500 or empty article

### ISSUE THREAD

**Issue by Zatalyz** [xif-fr/dokuwiki-plugin-catlist#2]
Hello,
I have a bug on my wiki and _maybe_ it is with catlist. But maybe not... 

I use catlist to generate menus automatically. Some users have problems viewing these pages. They get an error 500 per moment, at other times the wiki is displayed but the article appears empty. The same behavior exists with different machines and browsers:

- Windows 10 64-bit with Chrome 63 or Edge
- Ubuntu 17 with Iceweasel
- Archlinux with Links2

But a lot of other users haven't trouble...

In my Apache errors, I have the following mention:
`PHP Fatal error: Class' SafeFn' not found in /var/www/dokuwiki/lib/plugins/catlist/syntax. php on line 238, referer: https://khaganat.net/um1/fr:tag:geographie:start`

https://khaganat.net/um1/fr:tag:geographie:start being one of the pages that raises concerns. 

Catlist and Dokuwiki are up to date. However, we are on a Debian Jessie server, so with PHP in version 5. In addition, this wiki has a lot of plugins, an obsolete theme, and includes a navigation bar (top) which I also regularly worry about: all these faults could also explain the display error. 

The only Apache error mention catlist (for this part of the site), which is why I'm posting here, but I'll also try to solve the other problems.

Thanks a lot for your help and your good plugin :)

**Comment by xif-fr** [comment]
Hello, 
Could you try to add `require_once(DOKU_INC.'inc/SafeFN.class.php');` at line 17 of `syntax.php` ?
It should already be included, but maybe there's a issue with other plugins regarding this SafeFn class...

**Comment by Zatalyz** [comment]
Thanks, it seems work with this !

**Comment by xif-fr** [comment]
Ok thanks, I'll add the include systematically.
