### ISSUE TITLE
feature request: hide error message "dontexist"

### ISSUE THREAD

**Issue by jv-uzl** [xif-fr/dokuwiki-plugin-catlist#22]
It would be great to have an option to hide the error message if the given doesn't exist.

**Comment by xif-fr** [comment]
In the case the given namespace don't exist, what would you want to be displayed in place of the list ? Just nothing, or a "red link" ?

**Comment by jv-uzl** [comment]
For my current use case showing nothing would be best, but I understand this might not be the right thing for every body. Maybe code it in the option

`-showError  (default)` --> shows the current error/warning
`-showError:""`  --> show nothing
`-showError:"**Namespace doesn't exist**"` --> insert string as wiki text

**Comment by xif-fr** [comment]
This is a good idea. I'll implement it.

**Comment by xif-fr** [comment]
Finally, I just added the option `-hideNotFoundMsg`. Could you check if [this version](https://github.com/xif-fr/dokuwiki-plugin-catlist/archive/master.zip) fits your needs ?

**Comment by jv-uzl** [comment]
perfect, thanks a lot!

**Comment by xif-fr** [comment]
Ok, I will publish a new version one day.
