### ISSUE TITLE
The namespace does not exist

### ISSUE THREAD

**Issue by fama** [xif-fr/dokuwiki-plugin-catlist#23]
After adding <catlist> to any page, I get the error "The namespace does not exist"

I checked to make sure it's not ACL problem:  I suspect it's not the case as it's the admin user that gets this error.

**Comment by xif-fr** [comment]
What syntax do you use when invoking catlist ?

**Comment by fama** [comment]
Hello.  I tried various options:

- \<catlist\>
- \<catlist it:\>
- \<catlist .:\>

and tried with various namespaces (besides the workspace it: . 

I have the following plugins installed:
Bootstrap3 Template
oAuth Plugin
flowcharts Plugin
EditTable Plugin

It's a brand new install, so everything is the latest version.  In the catlist Plugin documentation, none of the above listed plugins are listed as conflicting.

In the end, I uninstalled the plugin catlist and using temporarily the simplenavi Plugin, which work OK.

**Comment by xif-fr** [comment]
Well, I have no idea, it should work. I'll try to replicate your install of dokuwiki.

**Comment by xif-fr** [comment]
I can't reproduce the error. On which system are you hosting your dokuwiki instance ?

**Comment by Himra** [comment]
Hello xif-fr,
I have the same problem after updating the catlist to the current version.
My system runs locally under apache
The same error after uninstalling and reinstalling 
The error is displayed both in the frontend and in the config and plugin area after saving.
I use `<catlist>` most of the time.

**Comment by xif-fr** [comment]
Are you running on Windows ?

Could you try to inject `msg($path, -1);` after the line 255 (after `utf8_encodeFN`) in `syntax.php` and check that the path displayed as an error message does really exist ?

**Comment by dolandemort** [comment]
I have been receiving this error as well. I am using Windows 10. I have inserted the line as you have instructed and received the following output:

```
C%3A/xampp/htdocs/dokuwiki/data/pages/logs
```

The actual path shown in my file explorer is:

```
C:\xampp\htdocs\dokuwiki\data\pages\logs
```

Hope this is what you were looking for.

**Comment by xif-fr** [comment]
Thanks !
Right, as I guessed, this is Windows-specific. I'll try to find a workaround. I may need your help to test the modification because I don't have any Windows set up.

**Comment by dolandemort** [comment]
> I may need your help to test the modification because I don't have any Windows set up.

No problem. Let me know whatever tests you want me to do.

**Comment by xif-fr** [comment]
Could you try the latest commit ?

**Comment by dolandemort** [comment]
It appears to have resolved the problem. Thanks!
