### ISSUE TITLE
Non-ASCII character cannot used in page name.

### ISSUE THREAD

**Issue by hrko** [xif-fr/dokuwiki-plugin-catlist#24]
When a page with a name which contains non-ascii characters is tried to add using this plugin, those characters will be converted to `_` and we cannot make a page with the desired name. 
![Screenshot from 2019-07-13 10-22-59](https://user-images.githubusercontent.com/18254610/61165275-42a08800-a559-11e9-92bb-3903593b4ba5.png)
![Screenshot from 2019-07-13 10-23-31](https://user-images.githubusercontent.com/18254610/61165279-54822b00-a559-11e9-9e51-0fca86280bbf.png)

Merging PR #10 can solve this problem.
![Screenshot from 2019-07-13 10-24-08](https://user-images.githubusercontent.com/18254610/61165285-5fd55680-a559-11e9-8505-ca94a501de83.png)

**Comment by xif-fr** [comment]
I'm not familiar with UTF-8 page names. The configuration setting `deaccent` is `off` in this case right ? If so, I need to take it into account. Thanks for the report.

**Comment by hrko** [comment]
Yes, but this problem happens regardless of the value of `deaccent`.

2019年7月13日(土) 17:50 Félix Faisant <notifications@github.com>:

**Comment by xif-fr** [comment]
Could you check the last version fits your needs ? It takes into account the `deaccent` configuration option to keep the former behavior when activated (which is the case by default)

**Comment by hrko** [comment]
The latest version is working properly as expected.
Thanks a lot!
