### ISSUE TITLE
sortByTitle problems with headlines starting with a digit [0-9]

### ISSUE THREAD

**Issue by hurzilein** [xif-fr/dokuwiki-plugin-catlist#29]
#30 

Hi

if u have for example 4 pages with the following titles (the first `<h1>`) 

1st page title:  **1. some text**
2nd page title: **2. some text**
3rd page title: **11. some text**
4th page title: **4. some text**

the result after sorting is 
- **1. some text**
- **11. some text**
- **2.**
- **4.**

replacing
`$b = strcmp($a_title, $b_title);`
with 					
`$b = strnatcasecmp($a_title, $b_title);`
in _syntax.php Line 344_
will do it but not tested for any side effects 

br

**Comment by xif-fr** [comment]
Thanks for the improvement. As the sorting feature was added very recently, I don't take much risk switching for `strnatcasecmp`.

**Comment by xif-fr** [comment]
Fixed by commit 0be92ea132dd11aa50941dd73d93d0fb8f9cb68c
New version soon
