### ISSUE TITLE
Sorting descending is broken since last update | inverting of strcmp

### ISSUE THREAD

**Issue by susnux** [xif-fr/dokuwiki-plugin-catlist#34]
Since last update the descending sort is broken.

Your code `$b = !$b` does not what you might think it does.

strcmp return <0 =0 or >0, so the correct code would be `$b *= -1`.

**Comment by xif-fr** [comment]
Oh right, this is embarrassing... I'll fix it tomorrow.

**Comment by xif-fr** [comment]
Fixed. Thanks again.
