### ISSUE TITLE
Feature: Allow namespace definition to be the "context" namespace

### ISSUE THREAD

**Issue by fwolfst** [xif-fr/dokuwiki-plugin-catlist#39]
When included in the sidebar, the relative namespace will always refer to the position of the sidebar.

```
:root
  |- sidebar
  |- page_in_root
  |-| :subnamespace
    |- page_in_sub
    |- ...
```

```
#sidebar
~~NOCACHE~~
<catlist .>
```

In the example structure given above (with `root` and `subnamespace` being namespaces), the sidebar will look the same when viewing `page_in_root` and `page_in_sub`.

It would be great if it would only render the "stuff" in `subnamespace` if rendered within.

IndexMenu solves this with a "context" option (search for "context" here: https://www.dokuwiki.org/plugin:indexmenu https://github.com/samuelet/indexmenu , code most likely here: https://github.com/samuelet/indexmenu/blob/ac677d3079574e0ff70fd16eabbc8126338f3524/syntax/indexmenu.php#L92).

An alternate implementation strategy might be to use another symbol to refer to the `context`, so instead of `.` and `..` use something like `*:..:` .

If its an ultra-low-hanging fruit I might look into crafting an PR if somebody guides me, but my php-fu is really weak.

**Comment by fwolfst** [comment]
I see that this is related to https://github.com/xif-fr/dokuwiki-plugin-catlist/issues/35 .

**Comment by xif-fr** [comment]
I'll look at it. I hope there's a DokuWiki variable somewhere storing the really rendered page.

The "another symbol" idea seems fine.

**Comment by fwolfst** [comment]
The PR at https://github.com/xif-fr/dokuwiki-plugin-catlist/issues/35 (https://github.com/xif-fr/dokuwiki-plugin-catlist/pull/36) does the job for me. When calling `<catlist %%CURRENT_NAMESPACE%%>` it will do exactly what I whished (I did not try with further references like `%%CURRENT_NAMESPACE%%:..:otherns:subns` etc.).

I do not know too much about dokuwiki, so I cannot judge where the symbolic value `%%CURRENT_NAMESPACE%%` fits into the conventions. One could also argue that "." itself should always be resolved to the NS/ID of the page viewed (and not of the "file" - which might included, like its the case in the sidebar).

**Comment by xif-fr** [comment]
I'm not willing to break the behavior of `.` for backwards compatibility, so I kept the `%%CURRENT_NAMESPACE%%` proposal.

I didn't realize at that time that the PR was exactly what you wanted. It's nice that you tested it.

I'll add this feature to the documentation.

**Comment by xif-fr** [comment]
Published it in the new version, tell me if it works.

**Comment by fwolfst** [comment]
Awesome. Works for me.
