### ISSUE TITLE
Sorting by title behaves conservatively when Umlauts are present

### ISSUE THREAD

**Issue by fwolfst** [xif-fr/dokuwiki-plugin-catlist#40]
When sorting by title, the sort order ("natural") does not behave as expected in other locales, e.g. German Umlauts (`Ä`) are expected to be near their relevant neighbour (`A`), but appear at the end of the list

The relevant code is at:
https://github.com/xif-fr/dokuwiki-plugin-catlist/blob/17186a024fdc796b1398f8afcc9cae7171948307/syntax.php#L343

I do not know PHP enough to understand which sorting function to use, maybe following thread helps:
https://stackoverflow.com/questions/9654907/php-array-sorting-with-accents

**Comment by xif-fr** [comment]
Thanks, I'll try to implement this with `Collator` (but in a optional fashion because it requires a module which is not always enabled).

**Comment by fwolfst** [comment]
Wow, that'd be cool. Looking at the stackoverflow Collator answer, it might be desirable to be able to define the locale independent of the system locale (i.e. in my case I know that the systems locale is not the locale in which I wish to have the sorting). But also I don't want to "throw work at you", just wanted to report what looked like a bug / missing feature at first sight.

**Comment by Klap-in** [comment]
DokuWiki includes now functions that utilizes the Collator now, including fallback. See
https://www.dokuwiki.org/devel:releases:refactor2021#sort_with_collator

I guess it could making implementation of this simpeler.

**Comment by xif-fr** [comment]
Oh, too bad I just added Collator-based sort yesterday !
I'll probably keep my implementation because I can tune the Collator options, but indeed I will probably replace `strnatcasecmp()` with DokuWiki's `Sort::strcmp()`.
Thanks for the heads up.
