### ISSUE TITLE
add page function

### ISSUE THREAD

**Issue by frdfrdfrdfrd** [xif-fr/dokuwiki-plugin-catlist#43]
clicked the add page button.
it created a page called currentnamespace:name_I_chose
is that what was supposed to happen. to be clear I wan in ht notes: namespace and did not get notes:page_I_wanted. maybe I did something wrong?

**Comment by xif-fr** [comment]
Could you be more precise on
- the page where catlist is used
- what syntax did you use for <catlist ...>

**Comment by frdfrdfrdfrd** [comment]
I click the add a page button
the list changes, and adds a [%%CURRENT_NAMESPACE%%:] as a non-linked item
on the page in the last position and gives me a box to type in.
I enter a name in the box then press ok.
I get a page with the name [current_namespace:what I entered] in edit mode.
I put some text on the page hit save. It is save with the name
[current_namespace:what I entered]
check site map, I have a new namespace named current_namespace.

of course I can move it, I just thought this was not intended.

square brackets added by me

I will help in anyway that I can if you need more information.
windows, wiki on a stick
latest dokuwiki when i checked a week or two ago.
plugins are current.


On Sun, Jan 2, 2022 at 6:01 PM Félix Faisant ***@***.***>
wrote:

> Could you be more precise on
>
>    - the page where catlist is used
>    - what syntax did you use for <catlist ...>
>

I cant read. sorry.
the page called from is "doc_notes:0_doc_notes"
<catlist -noAddPageButton -columns:3 %%CURRENT_NAMESPACE%%>
I get the %%CURRENT_NAMESPACE%% in the list and a box with an ok.
if i enter test_page in the box and press ok.
i go to a page "current_namespace:test_page" in edit mode.

sorry about not reading well enough, no excuse.

**Comment by frdfrdfrdfrd** [comment]
updated first comment.

**Comment by frdfrdfrdfrd** [comment]
is this a problem or am i doing something wrong?

**Comment by xif-fr** [comment]
Sorry for the late answer, I'm very busy at the moment.

This is indeed a problem with catlist, more precisely with the syntax `%%CURRENT_NAMESPACE%%`.
I will try to fix that.

In the meantime, you can just remove `%%CURRENT_NAMESPACE%%` from your `<catlist ...>` directive.
Typically, `%%CURRENT_NAMESPACE%%` is only for use in sidebars, when we want to display the real current namespace and not the namespace of the sidebar. But outside a sidebar, it is useless.

So just remove `%%CURRENT_NAMESPACE%%`.

**Comment by frdfrdfrdfrd** [comment]
Ok, thanks. I will reread the docs again. I honestly read over once and
copy and pasted what I thought I wanted.
Thanks for your reply. I don,t like being the noob, we all start somewhere.
again thanks.

**Comment by xif-fr** [comment]
No problem. You helped me spot a bug anyway ;)
