### ISSUE TITLE
add page button not work with chinese file name

### ISSUE THREAD

**Issue by qw918** [xif-fr/dokuwiki-plugin-catlist#44]
the add page button work fine with english file name. but if you use chinese file name, the file name will lost in the new page url.

test/test  ==>  test/test?do=edit
test/测试  ==>  test/?do=edit

my conf:
useslash=1
fnencode=utf-8
userewrite=1

**Comment by xif-fr** [comment]
Indeed, when catlist was written I though it was better to put page names in ascii. I'll add an option to disable this behavior. In the meantime, you can remove lines 36 to 49 in `script.js`.

**Comment by xif-fr** [comment]
Configuration option `pagename_sanitize` added by commit 86d76fd. Can be used to disable this unwanted behavior.
