### ISSUE TITLE
Turning on 'nocache' setting results in PHP warning 'undefined array key "title"'

### ISSUE THREAD

**Issue by dokuser** [xif-fr/dokuwiki-plugin-catlist#45]
Turning on 'Disable page cache where catlist is used' in the plugin configuration settings
(Which, in turn, adds the line '$conf['plugin']['catlist']['nocache'] = 1;' to the conf\local.php)

Gives the PHP warning: Undefined array key "title" in [...]\lib\plugins\catlist\syntax.php on line 403

**Comment by xif-fr** [comment]
Thanks for the bug report !
Fixed by commit d504141, will be included in the next version.
