### ISSUE TITLE
plugin.info.txt date information mismatch

### ISSUE THREAD

**Issue by geraldraaf** [xif-fr/dokuwiki-plugin-catlist#46]
Hi,
after update of dokuwiki and the plugins i used, i recognized that dokuwiki told me that there is an new **catlist** version from 2022-08-07 is available.
When i look in plugin.info.txt the date is on 2022-08-06

kind regards
Gerald

**Comment by xif-fr** [comment]
Thanks for averting me. I just mistyped the date, it is now fixed.
