### ISSUE TITLE
trouble excluding pages

### ISSUE THREAD

**Issue by roadrunnerjb** [xif-fr/dokuwiki-plugin-catlist#49]
Hi,
I'm trying to use this plugin to show some pages of a namespace. Assume we have pagenames starting with "v" others starting with "b" and some starting with "r".  I wanted to show the ones starting with 'v' so I used the following syntax:

`<catlist -sortDescending -noHead -noAddPageButton -excludeOnName -exclupage:"!^v" -columns:2>`

this gives me a result with all pages in this namespace, not what i expected. 

When I remove the "!" like this: 

`<catlist -sortDescending -noHead -noAddPageButton -excludeOnName -exclupage:"^v" -columns:2>`

I get a list of all pages except the excluded starting with "v" as I expect. 

So what am I doing wrong here ? Did I missunderstand the Syntax ?

Any help is welcome...

**Comment by slotwin** [comment]
The "!" is part of catlist syntax, not regex, and you should use it like this:

`<catlist -sortDescending -noHead -noAddPageButton -excludeOnName -exclupage!:"^v" -columns:2>`

**Comment by roadrunnerjb** [comment]
thank's for clarification it works now
