### ISSUE TITLE
feature request: Sort by title

### ISSUE THREAD

**Issue by bobafetthotmail** [xif-fr/dokuwiki-plugin-catlist#5]
Sorting by title is more useful than sorting by page ID, at least in the wiki I have.

**Comment by xif-fr** [comment]
I agree. But this feature requires substantial rewrite of the code, so it will wait a bit.

**Comment by bobafetthotmail** [comment]
Thanks for the answer. :+1:

**Comment by hurzilein** [comment]
maybe this quick hack without config option helps u for now



```
+++ syntax.php  2019-07-31 09:16:45.746068874 +0200
@@ -284,6 +284,7 @@
                        msg("catlist: can't open directory of namespace ".$ns, -1);
                        return;
                }
+               sort($scanDirs, SORT_NATURAL);
                foreach ($scanDirs as $file) {
                        if ($file[0] == '.' || $file[0] == '_') continue;
                        $name = utf8_decodeFN(str_replace('.txt', '', $file));
```

**Comment by xif-fr** [comment]
Well, catlist already do this type of sorting, by using the second argument of `scandir` :
```$scanDirs = @scandir($path, $data['scandir_sort']);```

When we say 'sort by title', it means sorting using the real _title_ of the page (the first `<h1>`) as generated by DokuWiki when showing links, not the filesystem name (page ID) of the page.

**Comment by xif-fr** [comment]
Implemented in the last version.
