### ISSUE TITLE
NoCache causes list to overwrite itself

### ISSUE THREAD

**Issue by its-markk** [xif-fr/dokuwiki-plugin-catlist#50]
Noticed that when we added a new namespace, it was not showing up right away.  Saw this is caused by the cache, and to use NoCache option.  When I either turn on NoCache or use the ~~NOCACHE~~ options, the tree of namespaces and pages will have the second column of 2, 3, or 4 columns have print over displaying on itself.  Seems to be just the top portion of the column.  Hitting CTRL F5 2 or 3 times seems to clear it up, until you add another namespace and page.

**Comment by xif-fr** [comment]
Hi,

Could you post some screenshots ?
