### ISSUE TITLE
Current namespace and the new page button

### ISSUE THREAD

**Issue by bh-chwo** [xif-fr/dokuwiki-plugin-catlist#52]
Hi, 
first, great plugin, use it a lot and we even removed all sidebar pages for your plugin. Since we need only the one on the root.

`<catlist %%CURRENT_NAMESPACE%% -smallHead -sortAscending -sortByTitle>`

these are the current options we use. The only thing not working is the "add a page..." button.
Because we use the _%%CURRENT_NAMESPACE%%_ option, the button tries to add a page to the _%%CURRENT_NAMESPACE%%_ namespace. And of course this namespace doesn't exist.

**Comment by xif-fr** [comment]
Hi,

Sorry for the long delay. The issue should be fixed by commit c8c9afd.
Thanks for using the plugin.
