### ISSUE TITLE
Warning: Undefined array key "creator" in ...

### ISSUE THREAD

**Issue by SmallRealities** [xif-fr/dokuwiki-plugin-catlist#56]
I installed the plugin using the extension manager and added <catlist> to a page. The page returns this error once for each item that should be in the catlist:

Warning: Undefined array key "creator" in c:\DokuWikiStick\dokuwiki\lib\plugins\catlist\syntax.php on line 279

I'm using the latest dokuwiki "kaos"

**Comment by xif-fr** [comment]
It is probably an incompatibility with this latest dokuwiki release.
It's a bit strange that nobody noticed before...
The contributor/creator metadata key seems to not be in use anywhere in the plugin, it should be safe to remove lines 278 and 279 in plugins\catlist\syntax.php. Can you try and tell me if it fixes the issue ?
Thanks in advance

**Comment by SmallRealities** [comment]
> It is probably an incompatibility with this latest dokuwiki release. It's a bit strange that nobody noticed before... The contributor/creator metadata key seems to not be in use anywhere in the plugin, it should be safe to remove lines 278 and 279 in plugins\catlist\syntax.php. Can you try and tell me if it fixes the issue ? Thanks in advance

I commented out 278-279 and the error disappears and the plugin works as expected. Thank you!

**Comment by xif-fr** [comment]
Fixed in commit 87f7093
