### ISSUE TITLE
Problem with listing

### ISSUE THREAD

**Issue by Stegadons** [xif-fr/dokuwiki-plugin-catlist#6]
catlist doesn't list pages in namespace.

Example:
Index - outside, inside
Let's say user has read permission on index pages for ns1 and ns2, and delete permission on namespace ns1:* and ns2:*
Wiki start page lists all available namespaces `<catlist -noAddPageButton -noHead -maxDepth:2>`

Output:
ns1
ns2

ns1 and ns2 links to their respective outside index
Index should list all pages and subnamespaces in ns `<catlist ns1: -addPageButtonEach -noHead >`, but for this user index is empty. It is possible to create new pages by using "Add a page..." button, but neither new or already existing pages are listed.
When viewing with admin user (has delete permission on *) all lists are fine.

**Comment by xif-fr** [comment]
Well, I'm not sure I understood precisely the problem, but it shouldn't do this. Do you have a working example on a wiki ?

**Comment by Stegadons** [comment]
I sent details to example in e-mail.

**Comment by xif-fr** [comment]
Did you received my e-mail back ?

**Comment by Stegadons** [comment]
Sorry for the long delay. Replied.

**Comment by xif-fr** [comment]
Fixed by commit #5f1a594
