### ISSUE TITLE
Catlist update

### ISSUE THREAD

**Issue by Superlibrarian** [xif-fr/dokuwiki-plugin-catlist#7]
Hi,
Thanks for the plugin, super useful, but what triggers it to update, though? When I create a page, it doesn't update the list right away, I've done a couple of tests and it looks like it's only updating when I delete a page. Would it be possible for it to update everytime a new page is created?
thanks

**Comment by xif-fr** [comment]
Hi, did you try the `nocache` catlist global option, or adding the `~~NOCACHE~~` directive ( https://www.dokuwiki.org/caching ) to the page ? The thing is that plugins are not in control of the cache, that's dokuwiki which triggers updates, not the plugins.

**Comment by Superlibrarian** [comment]
Hi, the nocache option worked, I hadn't seen it, thanks!

**Comment by xif-fr** [comment]
I'll make it clearer on the dokuwiki page.
