### ISSUE TITLE
Administration page become unavailable

### ISSUE THREAD

**Issue by Zatalyz** [xif-fr/dokuwiki-plugin-catlist#8]
Hello,
When plugin Catlist is added on the wiki, administration page (start?do=admin&page=config) become unavailable. If Catlist is deactivated, it is the same thing. The only way to retrieve the page is to uninstall the plugin. 

I have the bug on my old wiki after an update, so I try on a fresh install, I this bug appear when I install catlist, and disappears when I uninstall it.

**Comment by xif-fr** [comment]
That's annoying... What do you want to say exactly with "administration page become unavailable" ? White page ? 505 error ? Do you see anything strange in the PHP log ?

**Comment by luce-carevic** [comment]
Hi!

I have the same problem. The administration page becomes blank. I tried on my old wiki after an update also. I thought the install was the problem but I made a fresh install, same problem.

**Comment by xif-fr** [comment]
So it works with version 2018-06-24 ?
I can't manage to reproduce this bug on my wiki, I really need the PHP log.
Does the error still occurs when you get to the admin page from a page which does not use catlist ?

**Comment by Zatalyz** [comment]
I had a line in /var/log/apache2/error.log :) 

`[Sun Jul 22 20:32:23.389160 2018] [:error] [pid 21840] [client 109.190.202.194:63291] PHP Parse error:  syntax error, unexpected end of file in /var/www/bisdokuwiki/lib/plugins/catlist/lang/fr/settings.php on line 9, referer: https://mondomaine.com/bisdokuwiki/start?do=admin`

And... it's just a `;` who miss :)

**Comment by xif-fr** [comment]
Oh how can it be even possible to miss that >_<
Fixed by commit #e2c43f4 and by version 2018-07-22
Thanks !
